version: '3'

services:
  config-server:
    container_name: config-server
    image: hyness/spring-cloud-config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      - BANNER_LOCATION=file:/config/banner.txt
